# -*- coding: utf-8 -*-
"""clasificador_riesgo.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16Vu2A7sw38x3HHhNzVyGiv2_J62YZ_UF
"""

# Proyecto personal en Python para análisis básico de riesgo cardiovascular, orientado al aprendizaje de lógica médica aplicada a programación.

# 1.--> introduccion al programa
print ("Bienvenido al programa de control de riesgo cardiovascular")
print ("En este programa solicitaremos tu  peso (kg), talla (mts) y tension arterial y con esto podremos predecir tu riesgo cardiovascular")
print ("Por favor llena las siguientes casillas ")

# 2 --> definiendo la operatividad del programa.

# 2.1 --> definiendo la funcion y los puntos de corte para el peso
def imc (talla,peso):
  BMI = peso / (talla ** 2)
  print (" {:.2f}" .format (BMI))
  if BMI < 18.5:
    return "bajo peso"
  elif BMI < 25:
    return "normal"
  elif BMI < 30:
    return "sobrepeso"
  else:
    return "obesidad"

# 2.2 --> Definiendo la funcion de control y definicion de tension arterial
def control_ta (ta_diastolica, ta_sistolica):
  if ta_sistolica < 140 and ta_diastolica < 90:
    return "TA controlada"
  elif ta_sistolica >= 140 or ta_diastolica >= 90:
    return "TA no controlada"

# 2.3--> definiendo la funcion riesgo de acuerdo a resultados anteriores
def riesgo_cv (analizado_ta, analizado_imc):
  if analizado_ta == "TA no controlada" and analizado_imc in ["sobrepeso","obesidad"]:
    return "el riesgo es alto"
  elif analizado_ta == "TA controlada" and analizado_imc in ["normal","bajo peso"]:
    return "el riesgo es bajo"
  else:
    return ("EL riesgo es moderado")


# 3. ahora vamos a crear el modulo de ingreso de datos usando un bucle que asegure el ingreso de los datos.
while True:
  try:
    peso = int(input("Ingresa tu peso en kg: "))
    if peso > 0:
      break
    else:
      print ("el peso no es valido pues debe ser mayor a 0")
  except ValueError:
    print ("el peso no es valido pues debe ser un numero")

while True:
  try:
    talla = float(input("Ingresa tu altura en metros: "))
    if talla > 0:
      break
    else:
      print ("la talla no es valida pues debe ser mayor a 0")
  except ValueError:
    print ("la talla no es valida pues debe ser un numero")

while True:
  try:
    ta_sistolica = int(input("Ingresa tu presión arterial sistólica: "))
    if ta_sistolica > 0:
      break
    else:
      print ("la presion arterial sistolica no es valida pues debe ser mayor a 0")
  except ValueError:
    print ("la presion arterial sistolica no es valida pues debe ser un numero")

while True:
  try:
    ta_diastolica = int(input("Ingresa tu presión arterial diastólica:"))
    if ta_diastolica > 0:
      break
    else:
      print ("la presion arterial diastolica no es valida pues debe ser mayor a 0")
  except ValueError:
    print ("la presion arterial diastolica no es valida pues debe ser un numero")

#Definiendo la salida
analizado_imc = imc(talla, peso)
analizado_ta = control_ta(ta_diastolica, ta_sistolica)
riesgo = riesgo_cv(analizado_ta, analizado_imc)

print (f"el imc del paciente es de: {analizado_imc}")
print (f"la tension arterial del paciente es: {analizado_ta}")
print (f"el riesgo del paciente es: {riesgo}")